apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-container
spec:
  selector:
    matchLabels:
      app: backend-container
  template:
    metadata:
      labels:
        app: backend-container
    spec:
      containers:
      - name: backend-container
        image: kibunja/backend-server 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-container
spec:
  selector:
    app: backend-container
  ports:
  - port: 5000
    targetPort: 5000