apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yolo-database
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: mongodb-service
  replicas: 2
  template:
    metadata:
      labels:
        app: yolo-database
    spec:
      containers:
      - name: yolo-database
        image: mongo
        ports:
        - containerPort: 27017
          name: yolo-database
        volumeMounts:
        - name: mongo-datavol
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
