apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
spec:
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
      - name: app-frontend
        image: kibunja/frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app-frontend
  ports:
  - port: 3000
    targetPort: 3000
